# Generated by Django 3.2.5 on 2022-01-26 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Admin Provided Blog', max_length=150)),
                ('added_at', models.DateTimeField()),
                ('content_position', models.CharField(blank=True, max_length=10, null=True)),
                ('blog_url', models.SlugField(blank=True, null=True, unique=True)),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('Blog_categories', models.CharField(choices=[('General', 'General'), ('Cricket', 'Cricket'), ('Youtuber', 'Youtuber'), ('Actor', 'Actor'), ('SportPerson', 'SportPerson'), ('TechPerson', 'TechPerson'), ('Teacher', 'Teacher'), ('Health', 'Health'), ('God', 'God'), ('Safety', 'Safety'), ('Exam', 'Exam'), ('other', 'other')], default='General', max_length=15)),
                ('blog_rating', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='BlogRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
