# Generated by Django 3.2.5 on 2021-07-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField()),
                ('content_position', models.CharField(blank=True, max_length=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reward_claimed', models.DateField()),
                ('nested_balance', models.FloatField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('Referal_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
            ],
        ),
    ]
