# Generated by Django 3.2.5 on 2022-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='total_rate',
            field=models.IntegerField(default=0),
        ),
    ]
