# Generated by Django 3.2.5 on 2021-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descfields',
            old_name='image',
            new_name='descr',
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
