# Generated by Django 3.2.5 on 2021-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0003_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
