# Generated by Django 3.2.5 on 2021-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0004_blogs_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
