# Generated by Django 3.2.5 on 2021-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0005_blogs_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Blog_categories',
            field=models.CharField(choices=[('General', 'General'), ('Cricket', 'Cricket'), ('Youtuber', 'Youtuber'), ('Actor', 'Actor'), ('SportPerson', 'SportPerson'), ('TechPerson', 'TechPerson'), ('Teacher', 'Teacher'), ('other', 'other'), ('Health', 'Health')], default='General', max_length=15),
        ),
    ]
