# Generated by Django 3.2.5 on 2022-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0006_blogs_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_categories',
            field=models.CharField(choices=[('General', 'General'), ('Cricket', 'Cricket'), ('Youtuber', 'Youtuber'), ('Actor', 'Actor'), ('SportPerson', 'SportPerson'), ('TechPerson', 'TechPerson'), ('Teacher', 'Teacher'), ('Health', 'Health'), ('God', 'God'), ('Safety', 'Safety'), ('Exam', 'Exam'), ('other', 'other')], default='General', max_length=15),
        ),
    ]
