# Generated by Django 3.2.5 on 2022-01-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0007_alter_blogs_blog_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
