# Generated by Django 3.2.5 on 2022-01-25 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAPP', '0008_delete_customusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_rating_users',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
