# Generated by Django 3.2.5 on 2022-01-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAPP', '0009_auto_20220125_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_rating_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_rating_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
