# Generated by Django 3.2.5 on 2022-01-25 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAPP', '0010_alter_blogs_blog_rating_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_rating_users',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_rating_users',
            field=models.ManyToManyField(related_name='blog_rating_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
