# Generated by Django 3.2.5 on 2022-01-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0011_auto_20220125_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_rating_users',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_rating_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
