# Generated by Django 3.2.5 on 2022-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0012_auto_20220125_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_individual_ratings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
