# Generated by Django 3.2.5 on 2022-01-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAPP', '0013_blogs_blog_individual_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_individual_ratings',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_rating_users',
        ),
        migrations.CreateModel(
            name='BlogRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPP.blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
