# Generated by Django 3.2.5 on 2022-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0014_auto_20220125_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
