# Generated by Django 3.2.5 on 2022-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reward_claimed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
