# Generated by Django 3.2.5 on 2022-01-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_alter_user_last_reward_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nested_balance',
            field=models.FloatField(default=0),
        ),
    ]
