# Generated by Django 3.2.5 on 2022-01-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_alter_user_nested_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nested_balance',
            field=models.FloatField(default=1.0),
        ),
    ]
