# Generated by Django 3.2.5 on 2022-01-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_alter_user_nested_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
